/**
 * How big the model's fixed context is: the system prompt by section, and every tool definition, per surface.
 *
 * Pure measurement over what `captureSystemPrompt` returns, so it needs no engine. Sizes are in characters
 * (exact, deterministic) with an estimated token count next to them; the estimate uses one documented ratio,
 * so it is for comparing changes, not for billing. The committed ceilings (`plugins/acryl-system-prompt/drift/
 * budget.json`) make growth a deliberate decision.
 */

import type { CapturedSystemPrompt } from './system-prompt-capture.ts'

/**
 * Characters per token for this English-and-JSON mix. Calibrated once on the tool definitions, which are comparable, against the owner's measurement of the
 * ACRYL Web first turn (tool definitions about 8.7K tokens for 29,208 characters). The UI's system-prompt figure (about 4.6K) is larger than the
 * captured system message alone because it also counts what the workspace adds (instruction files, skill catalog), which this does not capture.
 */
export const CHARS_PER_TOKEN = 3.4

export interface SizedItem {
  readonly name: string
  readonly chars: number
}

export interface PromptBudget {
  readonly sections: readonly SizedItem[]
  readonly tools: readonly SizedItem[]
  readonly systemChars: number
  readonly toolsChars: number
}

/** Sections whose text names this machine (a checkout path, the working directory), so their size is not part of the budget. */
export const MACHINE_SPECIFIC_SECTIONS: ReadonlySet<string> = new Set(['harness_source', 'cwd'])

/** The system prompt's size without the machine-specific sections: the same on every checkout. */
export function stableSystemChars(budget: PromptBudget): number {
  return budget.sections.filter(section => !MACHINE_SPECIFIC_SECTIONS.has(section.name)).reduce((sum, section) => sum + section.chars, 0)
}

/** The ceiling to record for a measurement: its size rounded up to the next 100 characters. */
export function ceilingsFor(budget: PromptBudget): BudgetCeilings {
  const up = (chars: number): number => Math.ceil(chars / 100) * 100
  return { systemChars: up(stableSystemChars(budget)), toolsChars: up(budget.toolsChars) }
}

export function estimateTokens(chars: number): number {
  return Math.round(chars / CHARS_PER_TOKEN)
}

/** Split the assembled prompt into its identity paragraph and its `<tag>...</tag>` sections. */
export function splitSections(system: string): SizedItem[] {
  const sections: SizedItem[] = []
  const tag = /<([a-z_][a-z0-9_-]*)>\n?([\s\S]*?)\n?<\/\1>/g
  let cursor = 0
  for (const match of system.matchAll(tag)) {
    const index = match.index
    const head = system.slice(cursor, index).trim()
    if (head !== '') sections.push({ name: cursor === 0 ? 'identity' : 'untagged', chars: head.length })
    sections.push({ name: match[1] ?? 'section', chars: match[0].length })
    cursor = index + match[0].length
  }
  const tail = system.slice(cursor).trim()
  if (tail !== '') sections.push({ name: cursor === 0 ? 'identity' : 'untagged', chars: tail.length })
  return sections
}

export function measurePromptBudget(captured: CapturedSystemPrompt): PromptBudget {
  const tools = captured.tools
    .map(tool => ({ name: tool.name, chars: JSON.stringify(tool.definition).length }))
    .sort((a, b) => b.chars - a.chars || a.name.localeCompare(b.name))
  return {
    sections: splitSections(captured.system),
    tools,
    systemChars: captured.system.length,
    toolsChars: tools.reduce((sum, tool) => sum + tool.chars, 0),
  }
}

/** The ceilings the drift test enforces, per surface. */
export interface BudgetCeilings {
  readonly systemChars: number
  readonly toolsChars: number
}

/** @returns what exceeds its ceiling, in words; empty when within budget. */
export function overBudget(budget: PromptBudget, ceilings: BudgetCeilings): string[] {
  const problems: string[] = []
  const system = stableSystemChars(budget)
  if (system > ceilings.systemChars) {
    problems.push(`system prompt is ${String(system)} characters, over its ceiling of ${String(ceilings.systemChars)}`)
  }
  if (budget.toolsChars > ceilings.toolsChars) {
    problems.push(`tool definitions are ${String(budget.toolsChars)} characters, over their ceiling of ${String(ceilings.toolsChars)}`)
  }
  return problems
}

const row = (item: SizedItem): string => `| \`${item.name}\` | ${String(item.chars)} | ${String(estimateTokens(item.chars))} |`

/** Markdown of the per-section and per-tool table for each surface. */
export function renderBudgetDoc(bySurface: Readonly<Record<string, PromptBudget>>): string {
  const lines = [
    '# System prompt and tool budget',
    '',
    `<!-- Generated by the system-prompt capture (see README.md). Do not edit; regenerate. Tokens are estimated at ${String(CHARS_PER_TOKEN)} characters per token. -->`,
    '',
    'What the model is sent before the user says anything: the assembled system prompt (by section) and every tool definition (name, description and parameter schema).',
    'Characters are exact; tokens are an estimate for comparing changes. Ceilings live in `plugins/acryl-system-prompt/drift/budget.json`.',
    '',
  ]
  for (const [surface, budget] of Object.entries(bySurface)) {
    lines.push(`## ${surface}`, '',
      `Total: system prompt ${String(budget.systemChars)} chars (about ${String(estimateTokens(budget.systemChars))} tokens), tool definitions ${String(budget.toolsChars)} chars (about ${String(estimateTokens(budget.toolsChars))} tokens), ${String(budget.tools.length)} tools.`,
      '', '### System prompt by section', '', '| Section | Chars | Est. tokens |', '| --- | ---: | ---: |',
      ...budget.sections.map(row), '', '### Tool definitions, largest first', '', '| Tool | Chars | Est. tokens |', '| --- | ---: | ---: |',
      ...budget.tools.map(row), '')
  }
  return lines.join('\n')
}
