import { createHash } from 'node:crypto'
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'

/**
 * Automatic host-code hot reload (pi.dev clears its module cache on reload; Node cannot). Node caches an ES module by URL and caches the
 * package's resolution, so a re-installed plugin keeps running its OLD host code. The installer therefore installs a STAGED copy of the plugin:
 *
 *   <stage>/                    the author's package, unchanged (client.js, cordis.patch.yml, package.json without "files", ...)
 *   <stage>/<entry>             a generated wrapper (stable URL, cached) that, on EVERY activation, imports the newest versioned copy
 *   <stage>/acryl-v-<hash>/     a complete copy of the author's package, named by a hash of its contents
 *
 * Every version is a new directory, so the entry and everything it imports (helpers, sub-modules) have fresh URLs and are evaluated anew.
 * Metadata the loader reads at import time (`name`, `inject`, `Config`) comes from the first load; the wrapper warns when a later version
 * changes `inject`, which needs an app restart. Class-form `apply` (a Service subclass) cannot be wrapped and keeps its first version.
 * The author's source folder is never modified; `acryl-source.json` records where it is so `/reload` re-installs from it.
 */
export const VERSION_DIR_PREFIX = 'acryl-v-'
export const SOURCE_FILE = 'acryl-source.json'
const SKIP = new Set(['node_modules', '.git', SOURCE_FILE])

function walk(dir, visit, rel = '') {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP.has(entry.name) || entry.name.startsWith(VERSION_DIR_PREFIX)) continue
    const path = join(dir, entry.name)
    if (entry.isDirectory()) walk(path, visit, `${rel}${entry.name}/`)
    else visit(path, `${rel}${entry.name}`)
  }
}

/** A short content hash of the package's files (names and bytes), so an unchanged package keeps its version directory. */
export function hashPackage(dir) {
  const files = []
  walk(dir, (path, rel) => files.push([rel, path]))
  files.sort(([a], [b]) => (a < b ? -1 : 1))
  const hash = createHash('sha256')
  for (const [rel, path] of files) hash.update(rel).update('\0').update(readFileSync(path)).update('\0')
  return hash.digest('hex').slice(0, 10)
}

/** The entry file the loader imports, relative to the package root, or undefined when there is no JavaScript ES-module entry to wrap. */
export function entryOf(pkg) {
  const candidate = typeof pkg.exports?.['.'] === 'string' ? pkg.exports['.'] : typeof pkg.main === 'string' ? pkg.main : './index.js'
  return /\.(m?js)$/u.test(candidate) && pkg.type === 'module' || candidate.endsWith('.mjs') ? candidate.replace(/^\.\//u, '') : undefined
}

function shimSource(pkgName, entryRel) {
  return `// Generated by ACRYL (acryl_install_plugin) for automatic host-code hot reload. Do not edit: change the source folder and install again.
// Every activation imports the newest versioned copy of the plugin (acryl-v-*), so edits to host code and to the files it imports take
// effect without restarting the app. See docs/delivery/local-live.md in the extension pack.
import { readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const latest = () => {
  const dirs = readdirSync(here).filter(name => name.startsWith(${JSON.stringify(VERSION_DIR_PREFIX)})).sort()
  const target = pathToFileURL(join(here, dirs[dirs.length - 1], ${JSON.stringify(entryRel)})).href
  if (process.env.ACRYL_STAGE_DEBUG) console.error('[acryl-stage] importing', target, 'of', JSON.stringify(dirs))
  return target
}
const first = await import(latest())
const isClass = value => typeof value === 'function' && /^class[\\s{]/u.test(Function.prototype.toString.call(value))
const initialInject = JSON.stringify(first.inject ?? null)

export const name = first.name
export const inject = first.inject
export const Config = first.Config
export const apply = isClass(first.apply) || typeof first.apply !== 'function'
  ? first.apply
  : async function apply(ctx, config) {
    const current = await import(latest())
    if (JSON.stringify(current.inject ?? null) !== initialInject) {
      ctx.logger?.warn?.(${JSON.stringify(`[${pkgName}] "inject" changed since this app started: restart to apply it (the rest of the update is live).`)})
    }
    return current.apply(ctx, config)
  }
`
}

/**
 * Stage `sourceDir` for a hot-reloadable install.
 * @param {string} sourceDir the author's package directory (never modified)
 * @param {string} stageRoot directory that receives `<safe name>/`
 * @returns {{ ok: true, dir: string, version: string, name: string } | { ok: false, reason: string }}
 */
export function stagePackage(sourceDir, stageRoot) {
  let pkg
  try { pkg = JSON.parse(readFileSync(join(sourceDir, 'package.json'), 'utf8')) } catch { return { ok: false, reason: 'package.json is unreadable' } }
  const entryRel = entryOf(pkg)
  if (entryRel === undefined) return { ok: false, reason: 'the host entry is not a JavaScript ES module ("type": "module" and a .js/.mjs entry)' }
  if (!existsSync(join(sourceDir, entryRel))) return { ok: false, reason: `the host entry ${entryRel} does not exist` }
  const version = hashPackage(sourceDir)
  const safeName = String(pkg.name).replace(/[^A-Za-z0-9._-]+/gu, '_')
  const stamp = String(Date.now()).padStart(15, '0')
  // A UNIQUE path per install: pnpm treats an unchanged `file:` specifier as up to date and skips the copy even when the contents changed
  // (measured), so the dependency specifier itself must change on every install.
  const dir = join(stageRoot, `${safeName}@${stamp}`)
  mkdirSync(dir, { recursive: true })
  const copy = target => cpSync(sourceDir, target, { recursive: true, filter: source => !SKIP.has(basename(source)) && !basename(source).startsWith(VERSION_DIR_PREFIX) })
  copy(dir)
  // The timestamp prefix makes "newest" well defined even when the package manager leaves an older version directory behind.
  const versionDir = `${VERSION_DIR_PREFIX}${stamp}-${version}`
  copy(join(dir, versionDir))
  writeFileSync(join(dir, entryRel), shimSource(pkg.name, entryRel))
  // `files` would drop the versioned directory from the install; the staged package ships everything it contains.
  const { files: _files, ...staged } = pkg
  writeFileSync(join(dir, 'package.json'), `${JSON.stringify(staged, null, 2)}\n`)
  writeFileSync(join(dir, SOURCE_FILE), `${JSON.stringify({ source: sourceDir, version })}\n`)
  return { ok: true, dir, version, versionDir, name: pkg.name }
}

/** Where a staged install came from, or undefined for a plain install. */
export function stagedSource(installedDir, fs = { existsSync, readFileSync }) {
  try {
    const file = join(installedDir, SOURCE_FILE)
    if (!fs.existsSync(file)) return undefined
    const { source } = JSON.parse(fs.readFileSync(file, 'utf8'))
    return typeof source === 'string' ? source : undefined
  } catch { return undefined }
}


/**
 * Delete every versioned copy except the newest inside an INSTALLED staged package (best effort). Modules already evaluated stay in memory;
 * this only keeps the profile from accumulating one full copy of the plugin per update.
 */
export function pruneOldVersions(installedDir, keep, fs = { existsSync, readdirSync, rmSync }) {
  try {
    if (!fs.existsSync(installedDir)) return 0
    let removed = 0
    for (const name of fs.readdirSync(installedDir)) {
      if (name.startsWith(VERSION_DIR_PREFIX) && name !== keep) { fs.rmSync(join(installedDir, name), { recursive: true, force: true }); removed += 1 }
    }
    return removed
  } catch { return 0 }
}

/** Remove earlier staging copies of `packageName` (best effort), keeping only `keepDir`. */
export function pruneOldStages(stageRoot, packageName, keepDir, fs = { existsSync, readdirSync, rmSync }) {
  try {
    if (!fs.existsSync(stageRoot)) return 0
    const prefix = `${String(packageName).replace(/[^A-Za-z0-9._-]+/gu, '_')}@`
    let removed = 0
    for (const name of fs.readdirSync(stageRoot)) {
      const path = join(stageRoot, name)
      if (name.startsWith(prefix) && path !== keepDir) { fs.rmSync(path, { recursive: true, force: true }); removed += 1 }
    }
    return removed
  } catch { return 0 }
}
