/** Stable global class names shared by the lifecycle component and owned stylesheet. */
export const pluginLifecycleClasses = Object.freeze({
  section: 'dshPluginLifecycleSection',
  toolbar: 'dshPluginLifecycleToolbar',
  catalogHeading: 'dshPluginLifecycleCatalogHeading',
  cardHeader: 'dshPluginLifecycleCardHeader',
  summary: 'dshPluginLifecycleSummary',
  actions: 'dshPluginLifecycleActions',
  catalog: 'dshPluginLifecycleCatalog',
  search: 'dshPluginLifecycleSearch',
  cards: 'dshPluginLifecycleCards',
  card: 'dshPluginLifecycleCard',
  chevron: 'dshPluginLifecycleChevron',
  details: 'dshPluginLifecycleDetails',
  danger: 'dshPluginLifecycleDanger',
  protected: 'dshPluginLifecycleProtected',
  status: 'dshPluginLifecycleStatus',
  failure: 'dshPluginLifecycleFailure',
  architectureSummary: 'dshPluginArchitectureSummary',
  plane: 'dshPluginArchitecturePlane',
  planeHeader: 'dshPluginArchitecturePlaneHeader',
  stats: 'dshPluginArchitectureStats',
  fiberList: 'dshPluginArchitectureFiberList',
  fiber: 'dshPluginArchitectureFiber',
  fiberHeader: 'dshPluginArchitectureFiberHeader',
  fiberMeta: 'dshPluginArchitectureFiberMeta',
  phase: 'dshPluginArchitecturePhase',
  nativeDetails: 'dshPluginArchitectureNativeDetails',
  chips: 'dshPluginArchitectureChips',
  chip: 'dshPluginArchitectureChip',
  effectTree: 'dshPluginArchitectureEffectTree',
})
