// Real-execution test (spec 038-ui-component-library, T038): runs against the actual
// registry-seed generated by plugins/acryl-ui/scripts/generate-registry.mjs, not a fixture,
// so a real drift between the two implementations (this TS port and the proven standalone
// script) shows up here.
import { execFileSync } from 'node:child_process'
import { appendFileSync, existsSync, mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { runUiCommand } from '../src/host/ui-command.ts'

const uiPackageDir = resolve(fileURLToPath(import.meta.url), '..', '..', '..', '..', 'plugins', 'acryl-ui')
const registryDir = join(uiPackageDir, 'registry-seed')

beforeAll(() => {
  execFileSync('node', ['scripts/generate-registry.mjs'], { cwd: uiPackageDir })
})

describe('runUiCommand against the real generated registry', () => {
  it('list returns real items with real digests', () => {
    const result = runUiCommand({ action: 'list', registryDir })
    expect(result.kind).toBe('list')
    if (result.kind !== 'list') throw new Error('unreachable')
    expect(result.items.length).toBeGreaterThan(0)
    expect(result.items.some(item => item.id === 'acryl.ui.card')).toBe(true)
  })

  it('add copies real source, diff detects a real edit, re-add restores it', () => {
    const target = mkdtempSync(join(tmpdir(), 'acryl-ui-cli-add-'))
    try {
      const added = runUiCommand({ action: 'add', registryDir, id: 'acryl.ui.card', targetDir: target })
      expect(added.kind).toBe('add')
      if (added.kind !== 'add') throw new Error('unreachable')
      expect(added.surface).toBe('web')
      const cardFile = join(added.destDir, 'Card.tsx')
      expect(existsSync(cardFile)).toBe(true)

      const clean = runUiCommand({ action: 'diff', registryDir, id: 'acryl.ui.card', targetDir: target })
      expect(clean).toEqual({ kind: 'diff', id: 'acryl.ui.card', status: 'unchanged', changedFiles: [] })

      appendFileSync(cardFile, '\n// edited\n')
      const dirty = runUiCommand({ action: 'diff', registryDir, id: 'acryl.ui.card', targetDir: target })
      expect(dirty.kind).toBe('diff')
      if (dirty.kind !== 'diff') throw new Error('unreachable')
      expect(dirty.status).toBe('changed')
      expect(dirty.changedFiles.some(path => path.includes('Card.tsx'))).toBe(true)

      runUiCommand({ action: 'add', registryDir, id: 'acryl.ui.card', targetDir: target })
      expect(runUiCommand({ action: 'diff', registryDir, id: 'acryl.ui.card', targetDir: target }).kind).toBe('diff')
    } finally {
      rmSync(target, { recursive: true, force: true })
    }
  })

  it('rejects an unknown id and a surface the item does not have', () => {
    const target = mkdtempSync(join(tmpdir(), 'acryl-ui-cli-add-'))
    try {
      expect(() => runUiCommand({ action: 'add', registryDir, id: 'acryl.ui.nonexistent', targetDir: target })).toThrow('unknown registry item')
      expect(() => runUiCommand({ action: 'add', registryDir, id: 'acryl.ui.card', targetDir: target, surface: 'tui' })).toThrow("has no 'tui' surface")
    } finally {
      rmSync(target, { recursive: true, force: true })
    }
  })

  it('diff on a never-installed item reports not-installed rather than throwing', () => {
    const target = mkdtempSync(join(tmpdir(), 'acryl-ui-cli-add-'))
    try {
      expect(runUiCommand({ action: 'diff', registryDir, id: 'acryl.ui.dialog', targetDir: target }))
        .toEqual({ kind: 'diff', id: 'acryl.ui.dialog', status: 'not-installed', changedFiles: [] })
    } finally {
      rmSync(target, { recursive: true, force: true })
    }
  })
})

afterAll(() => {
  rmSync(registryDir, { recursive: true, force: true })
})
