// GENERATED by apps/acryl-cli/scripts/compile-palette.mjs from plugins/acryl-ui/contracts/tokens.json. Do not edit; change the token file and regenerate.

const dark = {
  primary: '#4F6BFE',
  secondary: '#38BDF8',
  accent: '#818CF8',
  reasoning: '#A855F7',
  success: '#34D399',
  warning: '#FBBF24',
  error: '#F87171',
  info: '#4F6BFE',
  muted: '#94A3B8',
}

const light = {
  primary: '#3652D9',
  secondary: '#0369A1',
  accent: '#4F46E5',
  reasoning: '#7E22CE',
  success: '#047857',
  warning: '#B45309',
  error: '#DC2626',
  info: '#3652D9',
  muted: '#64748B',
}

/** Terminal palettes by background: `dark` for a dark terminal (the default), `light` for a light one. */
export const palettes = { dark, light }
