/**
 * OPT-IN generator for `docs/system-prompt/current/*.md`: the system prompt and tool list the model actually receives, per surface.
 * Skipped unless `ACRYL_DUMP_SYSTEM_PROMPT` names an output directory. No model is called successfully: a dummy key makes the request
 * fail after the loop has already logged the assembled system message and the request header, which is all this reads.
 *
 *   ACRYL_DUMP_SYSTEM_PROMPT=docs/system-prompt/current corepack pnpm --filter acryl-harness-runtime exec vitest run tests/dump-system-prompt.spec.ts
 */
import { mkdirSync, mkdtempSync, realpathSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { provideCmdline } from '@deepseek-ai/dsh-cmdline'
import { SessionId } from '@deepseek-ai/dsh-session'
import { it } from 'vitest'
import { createDshEngineDefinition, createWebEngineDefinition } from '../src/engine-dsh.ts'
import { createAcrylEngineHost } from '../src/engine-host.ts'
import { createAcrylSessionBridge } from '../src/session-bridge.ts'

const outDir = process.env.ACRYL_DUMP_SYSTEM_PROMPT
const repoRoot = resolve(new URL('../../..', import.meta.url).pathname)

interface Captured { system: string; tools: Array<{ name: string; description: string }>; model: string }

async function capture(surface: 'web' | 'cli'): Promise<Captured> {
  process.env.DEEPSEEK_API_KEY = 'dummy-key-for-prompt-capture'
  process.env.DSH_HOME = mkdtempSync(join(tmpdir(), 'acryl-prompt-'))
  const workspace = mkdtempSync(join(tmpdir(), 'acryl-prompt-ws-'))
  const host = await createAcrylEngineHost(surface === 'cli'
    ? { engines: [createDshEngineDefinition('acryl-prompt')], initialEngine: 'dsh' }
    : {
        engines: [createWebEngineDefinition(new URL('../package.json', import.meta.url).href)],
        initialEngine: 'dsh',
        prepare: ctx => { provideCmdline(ctx, { args: ['--no-open', '--port', '0'], exit: () => {} }) },
      })
  const bridge = createAcrylSessionBridge(host.ctx, { profile: surface === 'cli' ? 'acryl-prompt' : 'web', generationId: 'prompt', attachment: 'owner', cwd: workspace })
  const captured: Captured = { system: '', tools: [], model: '' }
  try {
    const sessionId = await bridge.open()
    await bridge.selectModel({ sessionId, provider: 'deepseek-official', model: 'deepseek-v4-flash' })
    if (surface === 'web') {
      const presets = host.ctx.get('agentPresets' as never) as { select(agent: unknown, id: string): Promise<string> }
      const agent = (host.ctx as unknown as { agents: { get(id: unknown): unknown } }).agents.get(SessionId(sessionId))
      await presets.select(agent, 'standard')
    }
    let ended: () => void = () => {}
    const done = new Promise<void>(resolveDone => { ended = resolveDone })
    await bridge.subscribeEvents(sessionId, event => {
      const { type, data } = event as { type: string; data?: Record<string, unknown> }
      if (type === 'system/message' && captured.system === '') {
        const content = ((data?.message as { content?: Array<{ text?: string }> } | undefined)?.content ?? [])
        captured.system = content.map(block => block.text ?? '').join('')
      }
      if (type === 'request/header' && captured.tools.length === 0) {
        const header = data?.header as { tools?: Array<{ name: string; description: string }>; config?: { provider?: string; model?: string } } | undefined
        captured.tools = header?.tools ?? []
        captured.model = `${header?.config?.provider ?? ''}/${header?.config?.model ?? ''}`
      }
      if (type === 'turn/end') ended()
    })
    await bridge.submitPrompt({ sessionId, text: 'hello' })
    await Promise.race([done, new Promise(resolveTimeout => setTimeout(resolveTimeout, 60_000))])
  } finally {
    await bridge.dispose()
    await host.dispose()
  }
  const real = realpathSync(workspace)
  const scrub = (text: string): string => text
    .replaceAll(workspace, '<workspace>')
    .replaceAll(real, '<workspace>')
    .replaceAll(process.env.DSH_HOME ?? '\u0000', '<dsh-home>')
    .replaceAll(repoRoot, '<acryl-repo>')
  return { system: scrub(captured.system), tools: captured.tools.map(t => ({ name: t.name, description: scrub(t.description) })), model: captured.model }
}

function render(surface: string, c: Captured): string {
  const stamp = new Date().toISOString().slice(0, 10)
  return [
    `# Current system prompt: ${surface}`,
    '',
    `<!-- Generated by runtime/acryl-harness-runtime/tests/dump-system-prompt.spec.ts on ${stamp}. Do not edit; regenerate (see ../README.md). -->`,
    '',
    `What the model receives on the first turn of a new session on the ${surface} surface (${surface === 'web' ? 'standard preset' : 'terminal engine'}), after path scrubbing.`,
    'Temporary paths are shown as `<workspace>`, `<dsh-home>` and `<acryl-repo>`. The tool list follows the system prompt.',
    '',
    '## System prompt',
    '',
    '```text',
    c.system.trimEnd(),
    '```',
    '',
    `## Tools (${c.tools.length})`,
    '',
    '| Tool | Description (first line) |',
    '| --- | --- |',
    ...c.tools.map(t => `| \`${t.name}\` | ${t.description.split('\n')[0]?.replaceAll('|', '\\|').slice(0, 160) ?? ''} |`),
    '',
  ].join('\n')
}

it.skipIf(outDir === undefined)('dumps the current system prompt per surface', async () => {
  const dir = resolve(process.cwd(), '../..', outDir ?? '')
  mkdirSync(dir, { recursive: true })
  for (const surface of ['web', 'cli'] as const) writeFileSync(join(dir, `${surface}.md`), render(surface, await capture(surface)))
}, 240_000)
