/**
 * OPT-IN generator for `docs/system-prompt/current/{web,cli}.md`. Skipped unless `ACRYL_DUMP_SYSTEM_PROMPT` names an output directory
 * (relative to the repository root). Desktop is generated by `apps/acryl-desktop` (`corepack pnpm --filter acryl-desktop run dump:system-prompt`).
 *
 *   ACRYL_DUMP_SYSTEM_PROMPT=docs/system-prompt/current corepack pnpm --filter acryl-harness-runtime exec vitest run tests/dump-system-prompt.spec.ts
 */
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { provideCmdline } from '@deepseek-ai/dsh-cmdline'
import { it } from 'vitest'
import { createDshEngineDefinition, createWebEngineDefinition } from '../src/engine-dsh.ts'
import { createAcrylEngineHost } from '../src/engine-host.ts'
import { captureSystemPrompt, renderSystemPromptDoc } from '../src/system-prompt-capture.ts'

const outDir = process.env.ACRYL_DUMP_SYSTEM_PROMPT
const repoRoot = resolve(new URL('../../..', import.meta.url).pathname)

async function surface(kind: 'web' | 'cli'): Promise<string> {
  process.env.DEEPSEEK_API_KEY = 'dummy-key-for-prompt-capture'
  const home = mkdtempSync(join(tmpdir(), 'acryl-prompt-'))
  process.env.DSH_HOME = home
  const host = await createAcrylEngineHost(kind === 'cli'
    ? { engines: [createDshEngineDefinition('acryl-prompt')], initialEngine: 'dsh' }
    : {
        engines: [createWebEngineDefinition(new URL('../package.json', import.meta.url).href)],
        initialEngine: 'dsh',
        prepare: ctx => { provideCmdline(ctx, { args: ['--no-open', '--port', '0'], exit: () => {} }) },
      })
  try {
    const captured = await captureSystemPrompt(host.ctx, {
      profile: kind === 'cli' ? 'acryl-prompt' : 'web',
      selectStandardPreset: kind === 'web',
      scrub: [[home, '<dsh-home>'], [repoRoot, '<acryl-repo>']],
    })
    return renderSystemPromptDoc(kind === 'web' ? 'web' : 'cli', kind === 'web' ? 'standard preset' : 'terminal engine', captured)
  } finally { await host.dispose() }
}

it.skipIf(outDir === undefined)('dumps the current system prompt for web and cli', async () => {
  const dir = resolve(repoRoot, outDir ?? '')
  mkdirSync(dir, { recursive: true })
  for (const kind of ['web', 'cli'] as const) writeFileSync(join(dir, `${kind}.md`), await surface(kind))
}, 240_000)
