// Example: generated-capability.template
// Type:     generated-capability
// Surfaces: tui web desktop
// Teaches:  the shape of a publishable, reviewable capability: bundle patch, exports incl ./package.json, `acryl` manifest, acryl-package keyword, a header naming what it does.
// Expect:   ACRYL row ACTIVE; lists correctly in the marketplace once published (a human publishes).
// Docs:     extending.packaging
// Pattern:  acryldev.github.io scripts/lib/acryl-catalog.mjs
// Capability: example-capability
// Permissions: none (no network, no filesystem, no shell, no secrets)
// Generated by: <agent/session id>   Created: <date>   Based on: <examples used>
// Mutation class: HOT (a plugin remount is enough; no restart)
export const name = 'acryl-example-capability'

export function apply(ctx) {
  ctx.logger.info('[acryl-example-capability] active')
}
