export { findSecrets, type SecretFinding } from './secrets.js'
export { readAppIdentity, type AppIdentity, type Visibility } from './identity.js'
export type { GitPort, HostingPort } from './ports.js'
export { saveApp, type SaveResult } from './save.js'
export { connectRemote, type ConnectResult } from './connect.js'
export { PersistenceError, gitCli, githubHosting } from './adapters.js'
