// Generates src/tui/palette.generated.ts from the UI library's semantic role file (spec 038-ui-component-library, Q3 in research.md).
// One source, two targets: the web roles (@acryl/ui) and this terminal palette. Run `node scripts/compile-palette.mjs` after changing tokens.json;
// tests/palette.spec.ts fails when the committed output is stale. `--check` prints nothing and exits 1 when stale.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const here = new URL('.', import.meta.url)
const source = fileURLToPath(new URL('../../../plugins/acryl-ui/contracts/tokens.json', here))
const target = fileURLToPath(new URL('../src/tui/palette.generated.ts', here))
// The terminal component library carries the same palette as plain JS (it must work without the CLI, for a plugin that has no tuiTheme service).
const libraryTarget = fileURLToPath(new URL('../../../plugins/acryl-ui-tui/palette.js', here))

// Terminal role name for each semantic role that has a terminal color. The terminal owns its background and default text, so roles with null are skipped.
const TERMINAL_NAME = { primary: 'primary', secondary: 'secondary', accent: 'accent', reasoning: 'reasoning', success: 'success', warning: 'warning', error: 'error', info: 'info', textMuted: 'muted' }

export function renderPalette(tokens) {
  const lines = ['// GENERATED by scripts/compile-palette.mjs from plugins/acryl-ui/contracts/tokens.json. Do not edit; change the token file and regenerate.', '']
  for (const mode of ['dark', 'light']) {
    lines.push(`const ${mode} = {`)
    for (const [role, name] of Object.entries(TERMINAL_NAME)) {
      const hex = tokens.roles[role]?.terminal?.[mode]
      if (typeof hex !== 'string') throw new Error(`tokens.json: role ${role} has no ${mode} terminal color`)
      lines.push(`  ${name}: '${hex}',`)
    }
    lines.push('} as const', '')
  }
  lines.push('/** Terminal palettes by background: `dark` for a dark terminal (the default), `light` for a light one. */', 'export const palettes = { dark, light } as const', 'export type PaletteMode = keyof typeof palettes', 'export type Role = keyof typeof dark', '')
  return lines.join('\n')
}

const tokens = JSON.parse(readFileSync(source, 'utf8'))
const expected = renderPalette(tokens)
export function renderLibraryPalette(tokens) {
  return renderPalette(tokens)
    .replace('// GENERATED by scripts/compile-palette.mjs', '// GENERATED by apps/acryl-cli/scripts/compile-palette.mjs')
    .replace(/ as const/gu, '')
    .replace(/\nexport type [^\n]*/gu, '')
}
const expectedLibrary = renderLibraryPalette(tokens)
if (process.argv.includes('--check')) {
  const read = path => { try { return readFileSync(path, 'utf8') } catch { return '' } }
  process.exit(read(target) === expected && read(libraryTarget) === expectedLibrary ? 0 : 1)
}
if (import.meta.url === new URL(process.argv[1], 'file://').href || process.argv[1]?.endsWith('compile-palette.mjs')) { writeFileSync(target, expected); writeFileSync(libraryTarget, expectedLibrary) }
