// Generates src/tui/palette.generated.ts from the UI library's semantic role file (spec 038-ui-component-library, Q3 in research.md).
// One source, two targets: the web roles (acryl-ui-web) and this terminal palette. Run `node scripts/compile-palette.mjs` after changing tokens.json;
// tests/palette.spec.ts fails when the committed output is stale. `--check` prints nothing and exits 1 when stale.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const here = new URL('.', import.meta.url)
const source = fileURLToPath(new URL('../../../plugins/acryl-ui-web/contracts/tokens.json', here))
const target = fileURLToPath(new URL('../src/tui/palette.generated.ts', here))

// Terminal role name for each semantic role that has a terminal color. The terminal owns its background and default text, so roles with null are skipped.
const TERMINAL_NAME = { primary: 'primary', secondary: 'secondary', accent: 'accent', reasoning: 'reasoning', success: 'success', warning: 'warning', error: 'error', info: 'info', textMuted: 'muted' }

export function renderPalette(tokens) {
  const lines = ['// GENERATED by scripts/compile-palette.mjs from plugins/acryl-ui-web/contracts/tokens.json. Do not edit; change the token file and regenerate.', '']
  for (const mode of ['dark', 'light']) {
    lines.push(`const ${mode} = {`)
    for (const [role, name] of Object.entries(TERMINAL_NAME)) {
      const hex = tokens.roles[role]?.terminal?.[mode]
      if (typeof hex !== 'string') throw new Error(`tokens.json: role ${role} has no ${mode} terminal color`)
      lines.push(`  ${name}: '${hex}',`)
    }
    lines.push('} as const', '')
  }
  lines.push('/** Terminal palettes by background: `dark` for a dark terminal (the default), `light` for a light one. */', 'export const palettes = { dark, light } as const', 'export type PaletteMode = keyof typeof palettes', 'export type Role = keyof typeof dark', '')
  return lines.join('\n')
}

const expected = renderPalette(JSON.parse(readFileSync(source, 'utf8')))
if (process.argv.includes('--check')) {
  let current = ''
  try { current = readFileSync(target, 'utf8') } catch { /* missing */ }
  process.exit(current === expected ? 0 : 1)
}
if (import.meta.url === new URL(process.argv[1], 'file://').href || process.argv[1]?.endsWith('compile-palette.mjs')) writeFileSync(target, expected)
