// How a lock names the exact manifest it was generated from: the SHA-256 of the manifest file's bytes, as lowercase hex. One formula for every writer
// and reader of a lock (the engine's snapshot, `acryl new --from`, the registry's CI), so a lock generated by one is verified by another.
import { createHash } from 'node:crypto'

export function manifestDigest(manifestText: string): string {
  return createHash('sha256').update(manifestText).digest('hex')
}
